[package]
name = "local-ml"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
dotenvy = "0.15.7"
cpal = "0.17.1"
rodio = "0.21.1"

whisper-rs = "0.15.1"
llama-cpp-2 = "0.1.131"
webrtc-vad = "0.4.0"
ringbuf = "0.4.8"
rubato = "1.0.0"
hound = "3.5.1"
rand = "0.9.2"
ctrlc = "3.5"